### ISSUE TITLE
国内下载不了libwebp（0.6.0）

### ISSUE THREAD

**Issue by Eelson126** [Yeatse/KingfisherWebP#12]
国内下载不了libwebp（0.6.0）有其他源么

**Comment by Yeatse** [comment]
挂代理吧

**Comment by Yeatse** [comment]
解决办法：
1. 全局代理
2. 自建私有 pod 镜像
3. 手动修改libwebp下载地址，ref：http://www.lshxin.com/ios/2018/02/09/pod-%27libwebp%27-Error/
