### ISSUE TITLE
AnimatedWebP is not working

### ISSUE THREAD

**Issue by joelorenz20** [Yeatse/KingfisherWebP#13]
Hi,

I am trying to animated webp but it's not working.
I can only see the first frame of the animated webp.

here's my code:
`if let path = Bundle.main.path(forResource: "loader", ofType: "webp")  {`
`          let loader = AnimatedImageView()`
`          loader.kf.setImage(with: URL(fileURLWithPath: path))`
`          loader.startAnimating()`
 `}`

Note: KingfisherManager is set as a global default option in my AppDelegate.

I hope you can help me on this.

Thanks.

**Comment by Yeatse** [comment]
I just updated this library (#11 ) for better handling animated webp. You can KingfisherWebP to 0.4.0 to try this feature.

Any feedback is welcome.
