### ISSUE TITLE
Cocoapods use_modular_headers!

### ISSUE THREAD

**Issue by InsectQY** [Yeatse/KingfisherWebP#22]
Hi.
I use Cocoapods to install, but I have an error while compiling.

This is my Podfile
```ruby
use_modular_headers!

pod 'KingfisherWebP'
```
![dd7285b1-b757-4b6b-8336-f9836d6b9205](https://user-images.githubusercontent.com/22448409/50203966-27dcab00-039e-11e9-8931-48cdd1c70d28.png)

**Comment by InsectQY** [comment]
I know use this can solve my problem, but i don't want to generate a dynamic library.
Can you help me?
```ruby
use_frameworks!

pod 'KingfisherWebP'
```

**Comment by yichengchen** [comment]
Any progress or plan for fixing it?

**Comment by Yeatse** [comment]
@InsectQY @yichengchen Apologizes for this late reply 😂 Support for static library should be available in latest version.
