### ISSUE TITLE
load slow from disk cache

### ISSUE THREAD

**Issue by tzongw** [yeatse/KingfisherWebP#29]
load slow from disk cache,  set image completionHandler takes up to 10s to callback for a 5.5m webp animated image

**Comment by Yeatse** [comment]
Hi, would you mind sharing some example images for me to test?

**Comment by tzongw** [comment]
sure, I upload my test webp file to github, [https://github.com/tzongw/files/blob/master/animate.webp](url), you might need to download first

**Comment by FengDeng** [comment]
Please see  #35
