### ISSUE TITLE
Can't build KingfisherWebP.framework with prebuilded libwebp.framework

### ISSUE THREAD

**Issue by EldarShayahmetov** [Yeatse/KingfisherWebP#37]
I built libwebp framework via [iosbuild.sh](https://github.com/webmproject/libwebp/blob/master/iosbuild.sh) and imported using cocoapods as vendored framework to project. But i having problems with import paths in CGImage+WebP.m:
<img width="689" alt="Compile error" src="https://user-images.githubusercontent.com/36335477/87404370-ba6b1d80-c5c6-11ea-83f8-5a3ee21d44d7.png">

<img width="264" alt="Pods directory" src="https://user-images.githubusercontent.com/36335477/87404179-7c6df980-c5c6-11ea-8034-9ce683afa5b9.png">

If i change imports to:
#import "webp/demux.h" -> #import "webpdemux/demux.h"
#import "webp/mux.h" -> #import "webpmux/mux.h"
the error goes away, but i have problem with symbols for different archs (libwebp was build for all archs):

<img width="246" alt="Undefined symbols error" src="https://user-images.githubusercontent.com/36335477/87404820-4aa96280-c5c7-11ea-8729-55853a75db8d.png">

**Comment by Yeatse** [comment]
Hi, the `libwebp` depended by KingfisherWebP comes from [SDWebImage project](https://github.com/SDWebImage/libwebp-Xcode), which produces a single `libwebp.framework` instead of several separated frameworks. I assume prebuilding the libwebp.framework from this project could fix this issue.
