### ISSUE TITLE
KingfisherWebP framework schemes iOS

### ISSUE THREAD

**Issue by mkamranashfaq** [Yeatse/KingfisherWebP#40]
please resolve this issue.
Dependency "KingfisherWebP" has no shared framework schemes for any of the platforms: iOS

<img width="954" alt="Screenshot 2020-08-17 at 10 38 53 PM" src="https://user-images.githubusercontent.com/34715973/90426389-71811a00-e0da-11ea-8372-e8f1e6248f48.png">

**Comment by Yeatse** [comment]
Hello, which package manager are you using to add this library? CocoaPods or SPM? Would you mind proving a Podfile or Package.swift for me to reproduce this issue?

**Comment by mkamranashfaq** [comment]
I am using Carthage...
Tried different branches for #KingFisherwebP
github "Yeatse/KingfisherWebP" 
github "Yeatse/KingfisherWebP" "0.7.0"

**Comment by Yeatse** [comment]
Ah 😅 Carthage is not supported yet

**Comment by mkamranashfaq** [comment]
do you have any plan to make compatible this for Carthage 😅

**Comment by Yeatse** [comment]
Sorry for the late reply 😭 From version 1.0.0 KingfisherWebP can be used with Carthage now. See `README.md` for more details.
