### ISSUE TITLE
After loading webP, webP animation is delayed and the playback speed is abnormal

### ISSUE THREAD

**Issue by HelloHchen** [yeatse/KingfisherWebP#41]
I made a comparison with SDWebImageWebPCoder and found that the KingfisherWebP animation was not normal after being loaded. The webP resources are as follows:[home_broadcast.webp](http://file.hellohchen.com/home_broadcast.webp)

**Comment by Yeatse** [comment]
It's a known bug, we are still working on to resolve it. See #39 for more detail.

**Comment by HelloHchen** [comment]
I got it. Thank you
