### ISSUE TITLE
Occasional crash at WebPImageCreateWithData

### ISSUE THREAD

**Issue by kimi14314** [yeatse/KingfisherWebP#55]
Met an unusual crash. 
![企业微信截图_e985df83-d1bf-4593-a38d-576ee20e4316](https://user-images.githubusercontent.com/6508230/125747055-890c7e23-5138-4383-87f5-ab6441278bd5.png)

Any idea on what happened?

**Comment by kimi14314** [comment]
![企业微信截图_99157848-852a-47de-a55d-c8f43127d61f](https://user-images.githubusercontent.com/6508230/125747885-b8ec9dfa-0b0d-41e4-8a5c-8bbf18e12b37.png)

Crashed here

**Comment by skyxian** [comment]
> ![企业微信截图_99157848-852a-47de-a55d-c8f43127d61f](https://user-images.githubusercontent.com/6508230/125747885-b8ec9dfa-0b0d-41e4-8a5c-8bbf18e12b37.png)
> 
> Crashed here

Hello, have you solved this problem? I also encountered this problem, can you tell me how to solve it?

**Comment by kimi14314** [comment]
> > ![企业微信截图_99157848-852a-47de-a55d-c8f43127d61f](https://user-images.githubusercontent.com/6508230/125747885-b8ec9dfa-0b0d-41e4-8a5c-8bbf18e12b37.png)
> > Crashed here
> 
> Hello, have you solved this problem? I also encountered this problem, can you tell me how to solve it?

Hello, I tried to upgrade libwep to v1.2.0, but I am not sure if the problem could be solved since it's an unusual crash. Need to observe for a while

**Comment by Yeatse** [comment]
@skyxian @kimi14314 At what probability does it happen in production? I need more information to investigate into it, such as os version, more detailed stack traces etc.

**Comment by kimi14314** [comment]
![image](https://user-images.githubusercontent.com/6508230/133047399-735995c7-1457-432c-b1fa-7b84dd42abfa.png)
![image](https://user-images.githubusercontent.com/6508230/133047417-5cf56575-e11b-4067-83f3-531f8c0c5777.png)
"EXC_BAD_ACCESS · Attempted to dereference null pointer"
Seems to be a multi-thread problem. Probability is about 1% in production.


 
--


</a>"

**Comment by sunSink** [comment]
Has this problem been solved?  I also encountered this problem in production（KingfisherWebP version = 1.3.0 ,device model: = iPhone 8p，os = 14.7.1）, but i couldn't reproduce.

![image](https://user-images.githubusercontent.com/20489881/135188042-c7e928de-9b31-44d7-8ec2-2469569dda51.png)

**Comment by Yeatse** [comment]
> Has this problem been solved?  I also encountered this problem in production（KingfisherWebP version = 1.3.0 ,device model: = iPhone 8p，os = 14.7.1）, but i couldn't reproduce.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/20489881/135188042-c7e928de-9b31-44d7-8ec2-2469569dda51.png)
> 
> 

It shouldn't be a multithreaded problem, since webp decoding is totally a blocking operation. From this stack trace I assume it might be caused by some memory pressure. How much memory used and left on the device when this crash occurred?

**Comment by sunSink** [comment]
> > Has this problem been solved?  I also encountered this problem in production（KingfisherWebP version = 1.3.0 ,device model: = iPhone 8p，os = 14.7.1）, but i couldn't reproduce.
> > ![image](https://user-images.githubusercontent.com/20489881/135188042-c7e928de-9b31-44d7-8ec2-2469569dda51.png)
> 
> It shouldn't be a multithreaded problem, since webp decoding is totally a blocking operation. From this stack trace I assume it might be caused by some memory pressure. How much memory used and left on the device when this crash occurred?

![image](https://user-images.githubusercontent.com/20489881/135193950-f6ceac7a-ba15-4b38-b499-79f41affa736.png)

Thanks! 

Your guess may be correct.

**Comment by chenfeilaksa** [comment]
Is there any solution to this problem

**Comment by chenfeilaksa** [comment]
> > > 这个问题解决了吗？我在生产中也遇到过这个问题（KingfisherWebP version = 1.3.0 ,device model: = iPhone 8p，os = 14.7.1），但无法重现。
> > > ![图片](https://user-images.githubusercontent.com/20489881/135188042-c7e928de-9b31-44d7-8ec2-2469569dda51.png)
> > 
> > 
> > 它不应该是一个多线程问题，因为 webp 解码完全是一个阻塞操作。从这个堆栈跟踪我认为它可能是由一些内存压力引起的。发生此崩溃时，设备上已使用和剩余多少内存？
> 
> ![图片](https://user-images.githubusercontent.com/20489881/135193950-f6ceac7a-ba15-4b38-b499-79f41affa736.png)
> 
> 谢谢！
> 
> 你的猜测可能是正确的。

is there any solution，When the memory is low

**Comment by pengpai** [comment]
any update here? same issue at low memory case

**Comment by skyxian** [comment]
Previously, the use of webp was closed due to a crash. After the recent two versions were opened, this crash ranks in the top two positions. I can provide the following information. Can the author help analyze how to solve it?

**Comment by skyxian** [comment]
Previously, the use of webp was closed due to a crash. After the recent two versions were opened, this crash ranks in the top two positions. I can provide the following information. Can the author help analyze how to solve it?

![BIFpcsepYF](https://github.com/yeatse/KingfisherWebP/assets/9349361/3c23482a-cb9a-49ee-9b80-a601b6d73cad)

![UISWKj7M4b](https://github.com/yeatse/KingfisherWebP/assets/9349361/316ee82e-ec29-4184-8936-acc8ba22e738)
![GkY0DSCkEW](https://github.com/yeatse/KingfisherWebP/assets/9349361/0d63f3ed-7a2a-4355-a6f1-bafa23981c47)
![w4r6ZgROS3](https://github.com/yeatse/KingfisherWebP/asset
![JKMwDRgXMo](https://github.com/yeatse/KingfisherWebP/assets/9349361/6a89320a-72e9-485d-8711-3750ffdcbcf5)
s/9349361
![vCfVwvmhDU](https://github.com/yeatse/KingfisherWebP/assets/9349361/1cc75b48-3750-49d4-a9ad-eff1513d991a)

The crash seems to have occurred in models below iphoneXR，And it all happens in the WebPAnimDecoderDelete(dec) method

**Comment by skyxian** [comment]
> Actually this crash comes from the previous line: `memcpy(bufCopy, buf, bufsize);`. As we discussed earlier, this is fundamentally an out-of-memory issue, that we failed to copy the decoded image buffer for future use. In my personal experience, memory issues are more likely to occur on devices with 3GB RAM. For more details on this topic, please refer to [this article](https://satanwoo.github.io/2018/01/14/iOS-virtual/).
> 
> To resolve this crash and prevent similar issues in the future, you should pay close attention to your app's overall memory usage. Here are a couple of methods that can help:
> 
> 1. Set Kingfisher's memory cache to a lower limit: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#cache
> 2. Add a `ResizingImageProcessor` after `WebPProcessor` to downscale your result image
> 
> I will release a new version later that returns a null image instead of crashing when low memory occurs; however, it is still important for you to implement these changes.
> 
> @skyxian

Thank you very much, I will modify the existing code according to your suggestion, and look forward to your new release version

**Comment by yeatse** [comment]
Released 1.4.1

**Comment by chenfeilaksa** [comment]
> 现实上这个崩溃来自上一步：以`memcpy(bufCopy, buf, bufsize);`备将来使用。根据我的个人经验，内存问题更可能发生在配备了3GB RAM的设备上。有关于此主题的更多详细信息，请参阅[附件](https://satanwoo.github.io/2018/01/14/iOS-virtual/)。
> 
> 要解决此崩溃并阻止将出现类似问题，您应该密切注意应用的整体内存使用情况。以下是一些可以提供帮助的方法法：
> 
> 1. 将 Kingfisher 的内部存储设置为下载：[https ://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#cache](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#cache)
> 2. 添加一个`ResizingImageProcessor`after`WebPProcessor`以缩小小结果图像
> 
> 之后我会发布一个新版本，它会返回一个空间图像，而不是在内存不及时崩溃；但是，实际应用这些更改对您来说仍然很重要要。
> 
> @skyxian

"添加一个`ResizingImageProcessor`after`WebPProcessor`以缩小小结果图像" 

是这样设置吗：

options?.append(.processor(ResizingImageProcessor(referenceSize: size)))
options?.append(.processor(WebPProcessor.default))

**Comment by yeatse** [comment]
> > 现实上这个崩溃来自上一步：以`memcpy(bufCopy, buf, bufsize);`备将来使用。根据我的个人经验，内存问题更可能发生在配备了3GB RAM的设备上。有关于此主题的更多详细信息，请参阅[附件](https://satanwoo.github.io/2018/01/14/iOS-virtual/)。
> > 要解决此崩溃并阻止将出现类似问题，您应该密切注意应用的整体内存使用情况。以下是一些可以提供帮助的方法法：
> > 
> > 1. 将 Kingfisher 的内部存储设置为下载：[https ://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#cache](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#cache)
> > 2. 添加一个`ResizingImageProcessor`after`WebPProcessor`以缩小小结果图像
> > 
> > 之后我会发布一个新版本，它会返回一个空间图像，而不是在内存不及时崩溃；但是，实际应用这些更改对您来说仍然很重要要。
> > @skyxian
> 
> "添加一个`ResizingImageProcessor`after`WebPProcessor`以缩小小结果图像"
> 
> 是这样设置吗：
> 
> options?.append(.processor(ResizingImageProcessor(referenceSize: size))) options?.append(.processor(WebPProcessor.default))

Resizing 放 WebP 后面

**Comment by chenfeilaksa** [comment]
> 

这两个调换下先后  webp动图就不动了

**Comment by yeatse** [comment]
> 这两个调换下先后 webp动图就不动了

1.5.2 版本之后动图可以使用 AnimatedImageView 了，会自动根据 View 的实际大小压缩图片
