### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by CoderCMY** [yeatse/KingfisherWebP#59]
After transfer png to webp format image，Our App memory increase too much like the attachments below，I don't know why and how to fix it，Please give me some advise
![1 0](https://user-images.githubusercontent.com/42768920/138054571-b6588585-22dd-4740-846c-44bda5a22b72.png)
e
![1 1](https://user-images.githubusercontent.com/42768920/138054649-3d1ce2b1-4500-46ea-91fa-50faafe99153.png)
.

**Comment by CoderCMY** [comment]
> You can limit the memory cache used by Kingfisher following the instructions from [Kingfisher Cheat-Sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#set-limit-for-cache):
> 
> ```swift
> // Limit memory cache size to 20MB
> ImageCache.default.memoryStorage.config.totalCostLimit = 20 * 1024 * 1024
> ```
> 
> Feel free to feedback if it doesn't work.

I Just try many times , unfortunately It doesn't work ，My Image Limit Code is Like Below， I Don't Understand what caused the Memory rise too much once using webp format image when use the same configuration，If you find something please tell me.
```swift
    // 限制Kingfisher的内存和磁盘空间
    func configImageLimit(didReceiveMemoryWarning: Bool = false) {
        // 允许的内存缓存最大值
        var memoryCostLimit: Int = Int(ProcessInfo.processInfo.physicalMemory / 25)
        if didReceiveMemoryWarning {
		// 收到内存警告时，内存缓存减半
            	memoryCostLimit = memoryCostLimit / 2
        } else {
        	// 磁盘缓存最大值 150 MB
            	ImageCache.default.diskStorage.config.sizeLimit = 150 * 1024 * 1024
        }
        // 内存缓存最大值
        ImageCache.default.memoryStorage.config.totalCostLimit = memoryCostLimit
    } ```

**Comment by Yeatse** [comment]
I also noticed that from iOS 14 webp format has a built-in support. We're planning to implement this feature to reduce the memory footprint in iOS 14 devices.

**Comment by abhi21git** [comment]
I noticed some memory leaks in this library when used Instruments
