### ISSUE TITLE
加载本地webp有延迟

### ISSUE THREAD

**Issue by chenfeilaksa** [yeatse/KingfisherWebP#60]
加载本地的webp资源，首次展示有延迟

**Comment by chenfeilaksa** [comment]
let provider = LocalFileImageDataProvider(fileURL: imageURL!, cacheKey: "giftradio")
            self.kf.setImage(with: .provider(provider), options: options)

**Comment by Yeatse** [comment]
方便发一下图片吗，我本地调试下

**Comment by chenfeilaksa** [comment]
[合成1_00000_iSpt.webp.zip](https://github.com/Yeatse/KingfisherWebP/files/8029908/1_00000_iSpt.webp.zip)
好的，请查收

**Comment by Yeatse** [comment]
> 你好，这个问题调试的怎么样了

<img width="800" alt="image" src="https://user-images.githubusercontent.com/6036532/156509065-ec6a701f-5f5d-48fe-bc7e-9672ff4626a3.png">
我本地用 iPhone 8 跑了一下，这张图初次加载耗时 224ms，你是说这个延时吗？这个主要还是和 libwebp 库本地的效率有关吧

**Comment by Yeatse** [comment]
另外我看了一下这张图是个 23 帧的动图，可能加载时长与这个也有关系。目前 Kingfisher 还不支持第三方动态图渐近式加载，我后面看一下怎么优化下。

**Comment by chenfeilaksa** [comment]
> 另外我看了一下这张图是个 23 帧的动图，可能加载时长与这个也有关系。目前 Kingfisher 还不支持第三方动态图渐近式加载，我后面看一下怎么优化下。

我说的是从加载到看到它这个时长，那感觉是这个图的原因，谢谢了
