### ISSUE TITLE
When can support Carthage

### ISSUE THREAD

**Issue by broccolii** [Yeatse/KingfisherWebP#7]

**Comment by jbarros35** [comment]
why not?

**Comment by xiaofeiyun** [comment]
已经使用carthage集成了kingfisher,然后使用pods引入KingfisherWebP的时候，pods会重新引入一份kingfisher，请问有没有方法解决重复引入kingfisher的问题

**Comment by Yeatse** [comment]
Sorry for this terribly late reply 😂. From v1.0.0 KingfisherWebP can be used with Carthage now. See README.md for more details.
