### ISSUE TITLE
0-day issue with libwebp?

### ISSUE THREAD

**Issue by pparkppark** [yeatse/KingfisherWebP#71]
Hello?

0-day issue with libwebp
libwebp-xcode has fixed the issue and this library also requires an update.
https://github.com/SDWebImage/libwebp-Xcode/releases/tag/1.3.2

**Comment by yeatse** [comment]
This library does not impose any restrictions on the version of libwebp you are using. You can update your libwebp version by running `pod update` or navigating to `Xcode → File → Packages → Update to Latest Package Versions`.
