### ISSUE TITLE
 KingfisherWebP                      0x0000000103a46e6c WebPPictureImportCGImage + [CGImage+WebP.m : 79] 

### ISSUE THREAD

**Issue by LiuSky** [yeatse/KingfisherWebP#72]
KingfisherWebP                      0x0000000103a46e6c WebPPictureImportCGImage + [CGImage+WebP.m : 79]  线上崩溃很严重。

**Comment by LiuSky** [comment]
CrashDoctor Diagnosis: Application threw exception NSMallocException: Failed to grow buffer

**Comment by yeatse** [comment]
看起来是内存不足，没有详细调用栈和设备信息我无法给出进一步的结论

**Comment by LiuSky** [comment]
[error.txt](https://github.com/yeatse/KingfisherWebP/files/13302820/error.txt)
系统：ios
系统版本：iPadOS 16.7.2
机型版本：iPad12,1

**Comment by LiuSky** [comment]
@yeatse  我不理解，如果这张图片是png 格式的也会进入你这个函数。这是为什么？

**Comment by LiuSky** [comment]
我看了下有一张图片是png一张图片是jpeg格式的。但是都进入了你这个函数。正常来说不是webp的不进入这个函数才对。

**Comment by yeatse** [comment]
> 我看了下有一张图片是png一张图片是jpeg格式的。但是都进入了你这个函数。正常来说不是webp的不进入这个函数才对。
> 
> 

把WebPSerializer去掉试试

**Comment by LiuSky** [comment]
嗯。试过了。目前这个版本很稳定。
