### ISSUE TITLE
Crash on WebPImageCreateWithData

### ISSUE THREAD

**Issue by yycc** [yeatse/KingfisherWebP#73]
0	libsystem_platform.dylib
__platform_memmove + 76
1	KingfisherWebP
WebPImageCreateWithData + 160
2	KingfisherWebP
$s10Kingfisher0A7WrapperV0A4WebPSo7UIImageCRbzlE5image8webpData5scale14onlyFirstFrameAFSg10Foundation0G0V_12CoreGraphics7CGFloatVSbtFZAF_Tg5Tf4nnnd_n + 116
3	Kingfisher
$s10Kingfisher18ImageDataProcessorC9doProcess33_6119A2C527FFA834F85B326B80E79A62LLyyF + 604
4	Kingfisher
$s10Kingfisher18ImageDataProcessorC7processyyFyycACcfu_yycfu0_ + 20
5	Kingfisher
$s10Kingfisher13CallbackQueueO7executeyyyycFyyScMYccfU_TA + 20
6	Kingfisher
$sIegh_IeyBh_TRTm + 28
7	libdispatch.dylib
__dispatch_call_block_and_release + 32
8	libdispatch.dylib
__dispatch_client_callout + 20
9	libdispatch.dylib
__dispatch_lane_serial_drain + 748
10	libdispatch.dylib
__dispatch_lane_invoke + 380
11	libdispatch.dylib
__dispatch_root_queue_drain_deferred_wlh + 288
12	libdispatch.dylib
__dispatch_workloop_worker_thread + 404
13	libsystem_pthread.dylib
__pthread_wqthread + 288

**Comment by make1a** [comment]
I have the same issu 
![image](https://github.com/yeatse/KingfisherWebP/assets/17469549/2735a15e-bdd2-448a-a56d-a08f968f37f4)
![image](https://github.com/yeatse/KingfisherWebP/assets/17469549/8fc375d0-48ab-4a78-8ab4-36447abf5068)

**Comment by make1a** [comment]
@yeatse  可以修复它吗？ 这个崩溃是必现的

**Comment by yeatse** [comment]
> @yeatse 可以修复它吗？ 这个崩溃是必现的

这个和主楼不是一个问题，看上去是图片格式不兼容，辛苦新开一单，附带出问题的图片，谢谢

**Comment by yeatse** [comment]
@yycc It appears to be a memory issue that we recently fixed in the latest release. Could you please let us know the version of KingfisherWebP you are using? This will help us investigate further. Thank you.

**Comment by yycc** [comment]
@yeatse It appeared in 1.4.0 and 1.5.2

**Comment by yeatse** [comment]
Should have been fixed in v1.5.3
