### ISSUE TITLE
Kingfisher SDK 7.9.0 had include privacy manifest, can KingfisherWebP update the dependent version?

### ISSUE THREAD

**Issue by ZYHshao** [yeatse/KingfisherWebP#75]
hello 

now the KingfisherWebP dependent the Kingfisher SDK version is 7.8.1，Kingfisher had give a update for adapter Apple privacy policy, version is 7.9.0:

https://github.com/onevcat/Kingfisher/issues/2122

can KingfisherWebP update the dependent Kingfisher's version?

For more info, see:

[Describing data use in privacy manifests | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
[Describing use of required reason API | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
[Get started with privacy manifests - WWDC23 - Videos - Apple Developer](https://developer.apple.com/videos/play/wwdc2023/10060/)
Thanks!

**Comment by yeatse** [comment]
Hi! This library does not impose any restrictions on the version of Kingfisher you are using. You can update your Kingfisher to any version higher than 7.8.2 by running pod update or navigating to Xcode → File → Packages → Update to Latest Package Versions.

**Comment by yeatse** [comment]
Should be fixed in v1.5.4

**Comment by linhaosunny** [comment]
> Should be fixed in v1.5.4

it's v1.6.0 suppport this update? I have't see any commit

**Comment by linhaosunny** [comment]
> apple privacy policy

@yeatse  I update the lib by `pod 'KingfisherWebP', '1.6.0'` , but in Pods/KingfisherWebP ,I can't find Resources/PrivacyInfo.xcprivacy File, it's that ok ?

**Comment by yeatse** [comment]
> > apple privacy policy
> 
> @yeatse I update the lib by `pod 'KingfisherWebP', '1.6.0'` , but in Pods/KingfisherWebP ,I can't find Resources/PrivacyInfo.xcprivacy File, it's that ok ?

> https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
> You need to include a privacy manifest file in your third-party SDK if it’s listed in “SDKs that require a privacy manifest and signature,” in [Upcoming third-party SDK requirements](https://developer.apple.com/support/third-party-SDK-requirements/). Otherwise, include a privacy manifest file in your third-party SDK if it uses required reasons API, collects data about the person using apps that include the third-party SDK, enables the app to collect data about people using the app, or contacts tracking domains. Providing a privacy manifest file helps app developers to understand the API use and data-collection practices of your third-party SDK.


This library doesn't use any of those required reasons APIs, so I guess it's ok not to include a .xcprivacy file.

**Comment by linhaosunny** [comment]
> > > apple privacy policy
> > 
> > 
> > @yeatse I update the lib by `pod 'KingfisherWebP', '1.6.0'` , but in Pods/KingfisherWebP ,I can't find Resources/PrivacyInfo.xcprivacy File, it's that ok ?
> 
> > https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
> > You need to include a privacy manifest file in your third-party SDK if it’s listed in “SDKs that require a privacy manifest and signature,” in [Upcoming third-party SDK requirements](https://developer.apple.com/support/third-party-SDK-requirements/). Otherwise, include a privacy manifest file in your third-party SDK if it uses required reasons API, collects data about the person using apps that include the third-party SDK, enables the app to collect data about people using the app, or contacts tracking domains. Providing a privacy manifest file helps app developers to understand the API use and data-collection practices of your third-party SDK.
> 
> This library doesn't use any of those required reasons APIs, so I guess it's ok not to include a .xcprivacy file.

got it, thks
