### ISSUE TITLE
iOS 13 Image Cache Type: Memory - Flickering Issue with All WebPImage

### ISSUE THREAD

**Issue by make1a** [yeatse/KingfisherWebP#77]
```swift
            KingfisherManager.shared.defaultOptions += [
                .processor(WebPProcessor.default),
                .cacheSerializer(WebPSerializer.default)
            ]
```

https://github.com/onevcat/Kingfisher/issues/2188#issuecomment-1878283257

**Comment by make1a** [comment]
基本上所有的 webP图片在重复设置图片（如 `tableview.reloadData()`）的时候， 都会闪。这个问题现在卡住我的app不能上线，请问下能否给我一下建议修复这个问题？

**Comment by make1a** [comment]
我做了一个可以重现的demo： https://github.com/onevcat/Kingfisher/files/13840999/LaunchAPP.zip

**Comment by yeatse** [comment]
本地复现了一下 demo，设置 `ImageCache.default.memoryStorage.config.totalCostLimit = 1` 可以复现你的问题。

闪的原因是 `reloadData` 的时候触发 `imageView.kf.setImage`，默认会把 UIImageView **当前内容置空**，然后重新加载图片；

低端机内存不足，导致图片库跳过 `memoryStorage`，重新从磁盘读取解析图片；又由于低端机性能不足，webp 解码较为耗时，在解码过程中 UIImageView 是空白状态，导致看上去“闪了一下”。

解法是增加 `.keepCurrentImageWhileLoading` 选项，让 `imageView.kf.setImage` 不再置空当前图片即可。

**Comment by make1a** [comment]
我测试过增加 `.keepCurrentImageWhileLoading` ，或者 设置`placeholder = imageview.image` ， 在重复刷新下还是会闪的很厉害。 
同时还有一个问题 webP和非webP都会闪。
有其他解决方案吗？感激不尽

**Comment by yeatse** [comment]
闪的原因我上面已经说过了，options 不生效的原因你可以按照这个思路断点查下；另外还有一个可能是你的 cell 没有复用，可以尝试定位下。

如果找不到原因的话尝试去 WebPSerializer 去掉试试，还是不行的话我也没办法了，直接别用 webp 了

**Comment by make1a** [comment]
最终只能在底层兼容两套图片库了， iOS13 走sdwebImage ， iOS14 走kingfisher， 等项目升级到最低支持iOS14 再删掉SD。
