### ISSUE TITLE
Some WebPs don't play on IOS18

### ISSUE THREAD

**Issue by qgreat** [yeatse/KingfisherWebP#84]
guard let testString = String(data: testData, encoding: .ascii) else {
            return false
        }
    iOS18 May have more stringent validation of how strings and data are encoded. In this case, non-pure ASCII characters or abnormally encoded data may cause the conversion to fail.
    Some Webp files failed to convert to testString.

**Comment by yeatse** [comment]
This issue appears to have been resolved in https://github.com/yeatse/KingfisherWebP/pull/81. The patch has been published as version 1.6.1. Feel free to share any feedback on this version.
